services:
  - type: web
    name: shrinqo
    runtime: node
    plan: free
    buildCommand: npm install --omit=dev --ignore-scripts
    startCommand: node start.js
    envVars:
      - key: PORT
        value: "10000"
      - key: SITE_URL
        value: https://short.smp45.qzz.io
      - key: NODE_ENV
        value: production
