services:
  - type: web
    name: shrinqo
    runtime: node
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: node server.js
    envVars:
      - key: SITE_URL
        value: https://shrinqo.onrender.com
      - key: NODE_ENV
        value: production
